# Generated by Django 4.1.3 on 2022-11-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.CharField(max_length=20),
        ),
    ]
